=== duduklein/studiogdo/src/main/java/com/gdo/stencils/interpreted/stencil.dtd
<?xml version='1.0' encoding='iso-8859-1' ?>
<!--
Copyright 2005 StudioGdo/Guillaume Doumenc.
This software is the proprietary information of StudioGdo &amp; Guillaume Doumenc.
All rights reserved. Use is subject to license terms.
-->

<!-- DTD for the templatedescriptor -->
<!ELEMENT template (description*, params_description?, (param | inst | slot | command | plug | unplug | prop)*)>

<!-- DTD for the stencil descriptor -->
<!ELEMENT stencil (description*, params_description?, (inst | slot | command | plug | unplug | prop)*)>
<!ELEMENT inst (description*, params_description?, (param | inst | slot | command | plug | unplug | prop)*)>
<!ELEMENT command (description*, params_description?, (param | inst | slot | plug | unplug | prop)*)>

<!ELEMENT slot (description*, (proto | default | link | param)*)>
<!ELEMENT proto (description*)>
<!ELEMENT default (description*, (param | slot | command | plug | unplug | prop)*)>
<!ELEMENT link (description*)>

<!ELEMENT plug (description*)>
<!ELEMENT unplug (description*)>
<!ELEMENT prop (description*, data?)>

<!--
 Meta data used for description and gdodoc.
 -->
<!ELEMENT description (#PCDATA)>
<!ELEMENT params_description (param0?, param1?, param2?, param3?, param4?, example*)>
<!ELEMENT param0 (#PCDATA)>
<!ELEMENT param1 (#PCDATA)>
<!ELEMENT param2 (#PCDATA)>
<!ELEMENT param3 (#PCDATA)>
<!ELEMENT param4 (#PCDATA)>
<!ELEMENT example (#PCDATA)>

<!--
 A default instance is defined by its java class and
 initial parameters.
 -->
<!ELEMENT param (#PCDATA)>
<!ELEMENT data (#PCDATA)>

<!--
 A stencil template is associated to a java class which may not
 have the same name. Extension can be defined by java hierarchy
 or explicitly defined (used if defined).
 Facets redefined the facets file name associated.
 -->
<!ATTLIST template
	java CDATA #IMPLIED
	extends CDATA #IMPLIED
	facets CDATA #IMPLIED
>

<!--
 A stencil is defined by a template.
 -->
<!ATTLIST stencil
	template CDATA #REQUIRED
	id CDATA #IMPLIED
	name CDATA #IMPLIED
>

<!--
 A slot is defined by a name and an arity. It can be dual (parent is key)
 and ordoned (comparator)
 Then it can be transient (not stored), calculated (java defined)
 or delegate (link to another one slot; then local or not)
 -->
<!ATTLIST slot
	name CDATA #REQUIRED
	
	arity CDATA #IMPLIED
	parent CDATA #IMPLIED
	comparator CDATA #IMPLIED
	calculated (true|false) "false"
	transient (true|false) "false"

	factory CDATA #IMPLIED

	depends CDATA #IMPLIED
	
	final (true|false) "false"
	override (true|false) "true"

	delegate CDATA #IMPLIED
	local (true|false) "true"
>

<!ATTLIST prop
	name CDATA #REQUIRED
	type (int|boolean|string) "string"
 	
	file CDATA #IMPLIED
	id CDATA #IMPLIED
	
	expand (true|false) "false"
	transient (true|false) "false"
	calculated (true|false) "false"
	
	final (true|false) "false"
	override (true|false) "true"
>

<!-- WARNING : no command in command or you will get an stack error.. 
     as any stencil (then a command has an unplug command which is a stencil..)
-->
<!ATTLIST command
	name CDATA #REQUIRED
	template CDATA #IMPLIED
	
	final (true|false) "false"
	override (true|false) "true"
>

<!ATTLIST inst
	id CDATA #REQUIRED
	name CDATA #IMPLIED
	template CDATA #REQUIRED
	
	file CDATA #IMPLIED
	encoding CDATA #IMPLIED
>

<!ATTLIST plug
	ref CDATA #REQUIRED
	path CDATA #IMPLIED
	slot CDATA #REQUIRED
	key CDATA #IMPLIED
	on (create|load|always) "create"
>

<!ATTLIST unplug
	slot CDATA #REQUIRED
	key CDATA #IMPLIED
	on (create|load|always) "create"
>

<!ATTLIST link
	slot CDATA #REQUIRED
	key CDATA #IMPLIED
	path CDATA #REQUIRED
>

<!ATTLIST default
	template CDATA #REQUIRED
>

<!--
 Expected java classes (interfaces), slots or commands that must be
 defined to accept the plug.
 -->
<!ATTLIST proto
	classes CDATA #IMPLIED
	slots CDATA #IMPLIED
	commands CDATA #IMPLIED
	props CDATA #IMPLIED
	template CDATA #IMPLIED
>

<!--
 Parameter defined for java construction or command execution.
 -->
<!ATTLIST param
	index CDATA #REQUIRED
	type CDATA #REQUIRED
>

=== duduklein/studiogdo/src/main/java/com/gdo/user/cmd/ModifyMyself.xml
<?xml version='1.0' encoding='iso-8859-1' ?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<template java="com.gdo.user.cmd.ModifyMyself">

   <prop name="Title" type="string" file="com.gdo.user.prop" id="modify.title"/>

	<!-- faces steps -->
	<inst id="_1" template="com.gdo.project.model.StepStcl">
		<prop name="Title" type="string" file="com.gdo.user.prop" 
			id="modifyMyself.step1.title">
		</data></prop>
		<prop name="Render" type="string" file="com.gdo.user.prop" 
			id="modifyMyself.step1.render">
		</data></prop>
	</inst>
	<inst id="_2" template="com.gdo.project.model.StepStcl">
		<prop name="Title" type="string" file="com.gdo.user.prop"
			id="modifyMyself.step2.title">
		</data></prop>
		<prop name="Render" type="string" file="com.gdo.user.prop" 
			id="modifyMyself.step2.render">
		</data></prop>
	</inst>
	<plug ref="_1" key="1" slot="Steps" />
	<plug ref="_2" key="2" slot="Steps" />
</template>

=== duduklein/studiogdo/src/main/java/com/gdo/project/cmd/ModifySelected.xml
<?xml version='1.0' encoding='iso-8859-1' ?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<template extends="com.gdo.project.cmd.Selected">
	<description>
		Allow stencil modification.
		Select stencils from "Source"
		slots.
	</description>

	<!-- presentation part -->
	<prop name="Title" id="title" />

	<!-- Modification Step -->
	<inst id="_1" template="com.gdo.project.model.StepStcl">
		<prop name="Title" id="step1.title" />
		<prop name="Render" id="step1.render" />
	</inst>
	<inst id="_2" template="com.gdo.project.model.StepStcl">
		<prop name="Title" id="step2.title" />
		<prop name="Render" id="step2.render" />
	</inst>

	<plug ref="_1" key="1" slot="Steps" />
	<plug ref="_2" key="2" slot="Steps" />

</template>

=== duduklein/studiogdo/src/main/java/com/gdo/resource/model/DirectResourcesMgrStcl.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<template java="com.gdo.resource.model.DirectResourcesMgrStcl">

	<description>
		A resources manager which resources are directly the files and folders of the contexts.
	</description>
	
	<!-- default template for file/folder -->
	<prop name="FolderTemplate" type="string"><data>com.gdo.resource.model.DirectFolderResourceStcl</data></prop>
	<prop name="FileTemplate" type="string"><data>com.gdo.resource.model.DirectFileResourceStcl</data></prop>

	<!-- resources managed -->
	<slot name="FileResources" arity="*" calculated="true">
		<description>Delegated to Contexts/FilesOnly</description>
	</slot>
	<slot name="FolderResources" arity="*" calculated="true">
		<description>Delegated to Contexts/FoldersOnly</description>
	</slot>
	
</template>

=== duduklein/studiogdo/src/main/java/com/gdo/project/cmd/Selected.xml
<?xml version='1.0' encoding='iso-8859-1' ?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<template java="com.gdo.project.cmd.Selected">
	<description>
		Abstract class, just used as a common class for all
		selected command.
	</description>

	<!-- model part -->
	<slot name="Source" arity="*">
		<description>slot path where the selected stencils can be found (for
			selection)</description>
		<description>should be redefined (usually delegated slot)</description>
	</slot>

	<!-- selected stencils -->
	<slot name="Selected" arity="*">
		<description>slot where the selected stencils are plugged</description>
	</slot>

	<!-- used in rendering the command -->
	<prop name="StencilType" type="string">
		<data>stencil</data>
	</prop>

</template>

=== duduklein/studiogdo/src/main/java/com/gdo/resource/model/DirectFolderResourceStcl.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<template java="com.gdo.resource.model.DirectFolderResourceStcl">

	<description>
		The resource is directly created from the folder contained in the FolderEncapsulted.
	</description>
	<slot name="FolderEncapsulated" arity="1"/>

	<slot name="File" delegate="FolderEncapsulated"/>
	
	<!-- default template for file/folder -->
	<prop name="FolderTemplate" type="string"><data>com.gdo.resource.model.DirectFolderResourceStcl</data></prop>
	<prop name="FileTemplate" type="string"><data>com.gdo.resource.model.DirectFileResourceStcl</data></prop>

	<!-- resources managed -->
	<slot name="FileResources" calculated="true"/>
	<slot name="FolderResources" calculated="true"/>
	
</template>

=== duduklein/studiogdo/src/main/java/com/gdo/resource/model/FolderResourceStcl.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<template java="com.gdo.resource.model.FolderResourceStcl">

	<!-- resources managed -->
	<slot name="Resources" arity="*"/>
	<inst id="files" template="com.gdo.project.adaptor.LinkStcl">
  	<param index="0" type="string"><![CDATA[../FileResources]]></param>
	</inst>
	<inst id="folders" template="com.gdo.project.adaptor.LinkStcl">
  	<param index="0" type="string"><![CDATA[../FolderResources]]></param>
	</inst>
	<plug ref="files" slot="Resources"/>
	<plug ref="folders" slot="Resources"/>
	<slot name="FileResources" arity="*">
		<description>Contains all files managed</description>
		<!--link slot="ContainerManager" path="../ContainerManager"/>
		<link slot="ContainerFolder" path=".."/-->
	</slot>
	<slot name="FolderResources" arity="*">
		<description>Contains all folders managed</description>
		<!--link slot="ContainerManager" path="../ContainerManager"/>
		<link slot="ContainerFolder" path=".."/-->
	</slot>

	<slot name="Get" arity="*" calculated="true">
		<description>File defined at a given path as key (may be composed)</description>
	</slot>

</template>

=== duduklein/studiogdo/src/main/java/com/gdo/mail/cmd/AddAttachment.xml
<?xml version='1.0' encoding='iso-8859-1' ?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<template java="com.gdo.mail.cmd.AddAttachment">
	 
	<description>Attaches a resource to an email</description>
	
	<prop name="Type" type="int">
		<description>1=File, 2=Image(embed)</description>
	</prop>
	
	<inst id="1" template="com.gdo.project.model.StepStcl">
		<description>The user selects the resource to add.</description>
	</inst>
	<inst id="2" template="com.gdo.project.model.StepStcl">
		<description>Adds the resource to the mail.</description>
	</inst>
	
	<plug ref="1" key="1" slot="Steps"/>
	<plug ref="2" key="2" slot="Steps"/>
	 
	
</template>

=== duduklein/studiogdo/src/main/java/com/gdo/resource/model/ResourcesContainerStcl.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<template java="com.gdo.resource.model.ResourcesContainerStcl">

	<description>
		A resources container manages a list of resources.
	</description>
	
	<!-- context file proxy -->
	<slot name="Contexts" arity="*">
		<description>Contextes used to access resources (Get to retrieve one at any level, Files: to have the list of them at this level).</description>
		<proto slots="Files"/>
	</slot>

	<!-- resources managed -->
	<slot name="Files" arity="*" transient="true"/>
	<inst id="files" template="com.gdo.project.adaptor.LinkStcl">
  	<param index="0" type="string"><![CDATA[../FilesOnly]]></param>
	</inst>
	<inst id="folders" template="com.gdo.project.adaptor.LinkStcl">
  	<param index="0" type="string"><![CDATA[../FoldersOnly]]></param>
	</inst>
	<plug ref="files" slot="Files" on="always"/>
	<plug ref="folders" slot="Files" on="always"/>
	
	<slot name="FilesOnly" arity="*">
		<description>Contains all files managed</description>
	</slot>
	<slot name="FoldersOnly" arity="*">
		<description>Contains all sub containers managed</description>
	</slot>
	
	<slot name="Get" arity="*" calculated="true">
		<description>File defined at a given path as key (may be composed)</description>
	</slot>
	
</template>
