=== duduklein/studiogdo/src/main/java/com/gdo/stencils/interpreted/stencil.dtd
<?xml version='1.0' encoding='iso-8859-1' ?>
<!--
Copyright 2005 StudioGdo/Guillaume Doumenc.
This software is the proprietary information of StudioGdo &amp; Guillaume Doumenc.
All rights reserved. Use is subject to license terms.
-->

<!-- DTD for the templatedescriptor -->
<!ELEMENT template (description*, params_description?, (param | inst | slot | command | plug | unplug | prop)*)>

<!-- DTD for the stencil descriptor -->
<!ELEMENT stencil (description*, params_description?, (inst | slot | command | plug | unplug | prop)*)>
<!ELEMENT inst (description*, params_description?, (param | inst | slot | command | plug | unplug | prop)*)>
<!ELEMENT command (description*, params_description?, (param | inst | slot | plug | unplug | prop)*)>

<!ELEMENT slot (description*, (proto | default | link | param)*)>
<!ELEMENT proto (description*)>
<!ELEMENT default (description*, (param | slot | command | plug | unplug | prop)*)>
<!ELEMENT link (description*)>

<!ELEMENT plug (description*)>
<!ELEMENT unplug (description*)>
<!ELEMENT prop (description*, data?)>

<!--
 Meta data used for description and gdodoc.
 -->
<!ELEMENT description (#PCDATA)>
<!ELEMENT params_description (param0?, param1?, param2?, param3?, param4?, example*)>
<!ELEMENT param0 (#PCDATA)>
<!ELEMENT param1 (#PCDATA)>
<!ELEMENT param2 (#PCDATA)>
<!ELEMENT param3 (#PCDATA)>
<!ELEMENT param4 (#PCDATA)>
<!ELEMENT example (#PCDATA)>

<!--
 A default instance is defined by its java class and
 initial parameters.
 -->
<!ELEMENT param (#PCDATA)>
<!ELEMENT data (#PCDATA)>

<!--
 A stencil template is associated to a java class which may not
 have the same name. Extension can be defined by java hierarchy
 or explicitly defined (used if defined).
 Facets redefined the facets file name associated.
 -->
<!ATTLIST template
	java CDATA #IMPLIED
	extends CDATA #IMPLIED
	facets CDATA #IMPLIED
>

<!--
 A stencil is defined by a template.
 -->
<!ATTLIST stencil
	template CDATA #REQUIRED
	id CDATA #IMPLIED
	name CDATA #IMPLIED
>

<!--
 A slot is defined by a name and an arity. It can be dual (parent is key)
 and ordoned (comparator)
 Then it can be transient (not stored), calculated (java defined)
 or delegate (link to another one slot; then local or not)
 -->
<!ATTLIST slot
	name CDATA #REQUIRED
	
	arity CDATA #IMPLIED
	parent CDATA #IMPLIED
	comparator CDATA #IMPLIED
	calculated (true|false) "false"
	transient (true|false) "false"

	factory CDATA #IMPLIED

	depends CDATA #IMPLIED
	
	final (true|false) "false"
	override (true|false) "true"

	delegate CDATA #IMPLIED
	local (true|false) "true"
>

<!ATTLIST prop
	name CDATA #REQUIRED
	type (int|boolean|string) "string"
 	
	file CDATA #IMPLIED
	id CDATA #IMPLIED
	
	expand (true|false) "false"
	transient (true|false) "false"
	calculated (true|false) "false"
	
	final (true|false) "false"
	override (true|false) "true"
>

<!-- WARNING : no command in command or you will get an stack error.. 
     as any stencil (then a command has an unplug command which is a stencil..)
-->
<!ATTLIST command
	name CDATA #REQUIRED
	template CDATA #IMPLIED
	
	final (true|false) "false"
	override (true|false) "true"
>

<!ATTLIST inst
	id CDATA #REQUIRED
	name CDATA #IMPLIED
	template CDATA #REQUIRED
	
	file CDATA #IMPLIED
	encoding CDATA #IMPLIED
>

<!ATTLIST plug
	ref CDATA #REQUIRED
	path CDATA #IMPLIED
	slot CDATA #REQUIRED
	key CDATA #IMPLIED
	on (create|load|always) "create"
>

<!ATTLIST unplug
	slot CDATA #REQUIRED
	key CDATA #IMPLIED
	on (create|load|always) "create"
>

<!ATTLIST link
	slot CDATA #REQUIRED
	key CDATA #IMPLIED
	path CDATA #REQUIRED
>

<!ATTLIST default
	template CDATA #REQUIRED
>

<!--
 Expected java classes (interfaces), slots or commands that must be
 defined to accept the plug.
 -->
<!ATTLIST proto
	classes CDATA #IMPLIED
	slots CDATA #IMPLIED
	commands CDATA #IMPLIED
	props CDATA #IMPLIED
	template CDATA #IMPLIED
>

<!--
 Parameter defined for java construction or command execution.
 -->
<!ATTLIST param
	index CDATA #REQUIRED
	type CDATA #REQUIRED
>

=== duduklein/studiogdo/src/main/java/com/gdo/resource/model/ServerStcl.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<template java="com.gdo.resource.model.ServerStcl">

	<description>
		A resources server manages a list of resources.
		Children (sub resources servers) can be defined to allow structured service (search, list,..)
	</description>
	
	<!-- context file proxy -->
	<slot name="Contexts" arity="*">
		<description>Contextes used to access resources (Get to retrieve one at any level, Files: to have the list of them at this level).</description>
		<proto slots="Dir:Get:Files"/>
	</slot>

	<!-- manager hierarchy -->
	<slot name="Children" arity="*">
		<description>Resources subservers.</description>
	</slot>

	<!-- resources managed -->
	<slot name="Resources" arity="*" transient="true"/>
	<inst id="files" template="com.gdo.project.adaptor.LinkStcl">
  	<param index="0" type="string"><![CDATA[../FileResources]]></param>
	</inst>
	<inst id="folders" template="com.gdo.project.adaptor.LinkStcl">
  	<param index="0" type="string"><![CDATA[../FolderResources]]></param>
	</inst>
	<plug ref="files" slot="Resources" on="always"/>
	<plug ref="folders" slot="Resources" on="always"/>
	<slot name="FileResources" arity="*">
		<description>Contains all files managed</description>
		<link slot="ContainerManager" path=".."/>
		<link slot="ContainerFolder" path=".."/>
	</slot>
	<slot name="FolderResources" arity="*">
		<description>Contains all folders managed</description>
		<link slot="ContainerManager" path=".."/>
		<link slot="ContainerFolder" path=".."/>
	</slot>
	
	<slot name="ContainerManager" delegate="."/>
	<slot name="ContainerFolder" delegate="."/>

	<slot name="Get" arity="*" calculated="true">
		<description>File defined at a given path as key (may be composed)</description>
	</slot>

	<prop name="Url" type="string"/>
	
	<!-- resources commands -->
	<command name="AddResource" template="com.gdo.resource.cmd.AddResource"/>
	<command name="AddResourceInOneStep" template="com.gdo.resource.cmd.AddResourceInOneStep"/>
	<command name="NewResource" template="com.gdo.resource.cmd.AddResource">
	  <param index="0" type="string">new</param>
	  <param index="1" type="string">com.gdo.resource.model.FileResourceStcl</param>
	  <param index="2" type="string">true</param>
	</command>
	<!-- <command name="AddImage" template="com.gdo.resource.cmd.AddResource">
	  <param index="0" type="string">com.gdo.image.model.ImageStcl</param>
	  <param index="1" type="string">Resources</param>
	  <param index="2" type="string">Contexts</param>
	</command>
	<command name="AddDocument" template="com.gdo.resource.cmd.AddResource">
	  <param index="0" type="string">com.gdo.document.model.DocumentStcl</param>
	  <param index="1" type="string">Resources</param>
	  <param index="2" type="string">Contexts</param>
	</command> -->
	
	<command name="CreateContext" template="com.gdo.resource.cmd.CreateContext"/>

	<command name="AddChild" template="com.gdo.project.cmd.CreateAtomic">
	  <param index="0" type="string"><![CDATA[com.gdo.resource.model.ResourcesMgrStcl]]></param>
	  <param index="1" type="string"><![CDATA[Target/Children]]></param>
	  <param index="2" type="string"><![CDATA[int]]></param>
	</command>
	
</template>

=== duduklein/studiogdo/src/main/java/com/gdo/project/cmd/Connect.xml
<?xml version='1.0' encoding='iso-8859-1' ?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<!-- Test a user connection : check login/paswd and set the user in /Session/User. 
	The users are defined in slot Users (except dev user defined in code) -->
<template java="com.gdo.project.cmd.Connect">
	<description>
		Test a user for connection. 
	</description>
	<params_description>
		<param0>The user login (if login is null then login access, if login
			is "" then anonymous access)</param0>
		<param1>The user passwd</param1>
		<param2>Template class name for user plugged in /Session/User</param2>
		<param3>Anonymous login path ("/" by default)</param3>
		<param4>Anonymous login mode ("login" by default)</param4>
	</params_description>

	<prop name="UserTemplate" type="string" />

	<slot name="Users" arity="*">
		<description>Users defined for login</description>
		<proto props="Name:Passwd:Path:Mode" />
	</slot>

</template>

=== duduklein/studiogdo/src/main/java/com/gdo/stencils/facet/FacetsStcl.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<template java="com.gdo.project.Stcl">

	<slot name="label" arity="*">
		<description>List of label facets (mode as key)</description>
		<proto classes="com.gdo.stencils.prop.IProperty" />
	</slot>

	<slot name="panel" arity="*">
		<description>List of label facets (mode as key)</description>
		<proto classes="com.gdo.stencils.prop.IProperty" />
	</slot>

	<slot name="tree" arity="*">
		<description>List of label facets (mode as key)</description>
		<proto classes="com.gdo.stencils.prop.IProperty" />
	</slot>

	<slot name="flex" arity="*">
		<description>List of label facets (mode as key)</description>
		<proto classes="com.gdo.stencils.prop.IProperty" />
	</slot>

	<slot name="model" arity="*">
		<description>List of label facets (mode as key)</description>
		<proto classes="com.gdo.stencils.prop.IProperty" />
	</slot>

</template>

=== duduklein/studiogdo/src/main/java/com/gdo/mail/cmd/SendComposed.xml
<?xml version='1.0' encoding='iso-8859-1' ?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<template java="com.gdo.mail.cmd.SendComposed">
	 
	<description>Simple mail composed command</description>
	
	<inst id="1" template="com.gdo.project.model.StepStcl">
		<description>The user must be able to send simple mail.</description>
	</inst>
	<inst id="2" template="com.gdo.project.model.StepStcl">
		<description>Step sends the mail and show the message.</description>
	</inst>
	<plug ref="1" key="1" slot="Steps"/>
	<plug ref="2" key="2" slot="Steps"/>
	
</template>

=== duduklein/studiogdo/src/main/java/com/gdo/resource/direct/DateOrderedFolderResourceStcl.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<template extends="com.gdo.resource.model.DirectFolderResourceStcl">

	<description>
		Files are sorted by date and folders by name.
	</description>
	
	<!-- default template for folder -->
	<prop name="FolderTemplate" type="string"><data>com.gdo.resource.direct.DateOrderedFolderResourceStcl</data></prop>

	<!-- resources managed -->
	<slot name="FileResources" arity="*" calculated="true" comparator="gnirts[LastModified]">
		<description>Contains all files managed</description>
	</slot>
	
	<slot name="FolderResources" arity="*" calculated="true" comparator="string[Name]">
		<description>Contains all folders managed</description>
	</slot>

</template>

=== duduklein/studiogdo/src/main/java/com/gdo/project/cmd/DeleteSelected.xml
<?xml version='1.0' encoding='iso-8859-1' ?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<template java="com.gdo.project.cmd.DeleteSelected">
	<description>
		Deletes a stencil from a selected slot.
		The java methods
		beforeUnplug may be redefined for specific stencil deletion. 
	</description>
	<params_description>
		<param0>deletion step (at which step index the stencil will be
			deleted)</param0>
		<example><![CDATA[
    	<template extends="com.gdo.project.cmd.DeleteSelected">
				<param index="0" type="int">2</param> <!-- no confirmation -->
			</template>
		]]></example>
	</params_description>

	<!-- model part -->
	<param index="0" type="int"><![CDATA[3]]></param>

	<slot name="Source" arity="*">
		<description>slot path where the selected stencils can be found (for
			selection)</description>
		<description>should be redefined (usually delegated slot)</description>
	</slot>

	<!-- used in rendering the command -->
	<prop name="StencilType" type="string">
		<data>stencil</data>
	</prop>

	<!-- presentation part -->
	<prop name="Title" id="title" />

	<!-- Selection Step -->
	<inst id="_1" template="com.gdo.project.model.StepStcl">
		<prop name="Title" id="step1.title" />
		<prop name="Render" id="step1.render" />
	</inst>

	<!-- Deletion Step -->
	<inst id="_2" template="com.gdo.project.model.StepStcl">
		<prop name="Title" id="step2.title" />
		<prop name="Render" id="step2.render" />
	</inst>

	<plug ref="_1" key="1" slot="Steps" />
	<plug ref="_2" key="2" slot="Steps" />

</template>

=== duduklein/studiogdo/src/main/java/com/gdo/mail/cmd/MultiSendMail.xml
<?xml version='1.0' encoding='iso-8859-1' ?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<template java="com.gdo.mail.cmd.MultiSendMail">
	<description>
		Send the mail. Parameters can be used to override fields (multiple parameters are ':' separated).
	</description>
	<params_description>
		<param0>Title</param0>
		<param1>From</param1>
		<param2>To</param2>
		<param3>CC</param3>
		<param4>Content</param4>
	</params_description>
</template>

=== duduklein/studiogdo/src/main/java/com/gdo/mail/model/FolderStcl.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<template java="com.gdo.mail.model.FolderStcl">

	<prop name="FolderTemplate" type="string"><data>com.gdo.mail.model.FolderStcl</data></prop>
	<prop name="FileTemplate" type="string"><data>com.gdo.mail.model.IMAPMailStcl</data></prop>

	<slot name="Context" arity="1"/>
	
	<slot name="Parent" arity="1"/>

	<slot name="Files" arity="*" transient="true">
		<description>Files and folders defined in the directory</description>
	</slot>
	<inst id="folders" template="com.gdo.project.adaptor.LinkStcl">
		<prop name="Path" type="string"><data>../FoldersOnly</data></prop>
	</inst>
	<inst id="files" template="com.gdo.project.adaptor.LinkStcl">
		<prop name="Path" type="string"><data>../FilesOnly</data></prop>
	</inst>
	<plug ref="folders" slot="Files"/>
	<plug ref="files" slot="Files"/>
	
	<slot name="FilesOnly" arity="*" calculated="true">
		<description>Files only defined in the directory</description>
		<proto slots="Name"/>
	</slot>
	
	<slot name="FoldersOnly" arity="*" calculated="true">
		<description>Folders only defined in the directory</description>
		<proto slots="Name"/>
	</slot>

	<slot name="AttachmentsOnly" arity="*" calculated="true">
		<description>Files only defined in the attachments</description>
		<proto slots="Name"/>
	</slot>
	
	<slot name="Get" arity="*" calculated="true">
		<description>File defined at a given path as key (may be composed)</description>
		<proto slots="Name" commands="Delete:Rename"/>
	</slot>
	
	<!-- command name="Delete" template="com.gdo.mail.cmd.Delete"/>
	<command name="Rename" template="com.gdo.mail.cmd.RenameFolder"/-->

</template>
