=== duduklein/studiogdo/src/main/java/com/gdo/stencils/interpreted/stencil.dtd
<?xml version='1.0' encoding='iso-8859-1' ?>
<!--
Copyright 2005 StudioGdo/Guillaume Doumenc.
This software is the proprietary information of StudioGdo &amp; Guillaume Doumenc.
All rights reserved. Use is subject to license terms.
-->

<!-- DTD for the templatedescriptor -->
<!ELEMENT template (description*, params_description?, (param | inst | slot | command | plug | unplug | prop)*)>

<!-- DTD for the stencil descriptor -->
<!ELEMENT stencil (description*, params_description?, (inst | slot | command | plug | unplug | prop)*)>
<!ELEMENT inst (description*, params_description?, (param | inst | slot | command | plug | unplug | prop)*)>
<!ELEMENT command (description*, params_description?, (param | inst | slot | plug | unplug | prop)*)>

<!ELEMENT slot (description*, (proto | default | link | param)*)>
<!ELEMENT proto (description*)>
<!ELEMENT default (description*, (param | slot | command | plug | unplug | prop)*)>
<!ELEMENT link (description*)>

<!ELEMENT plug (description*)>
<!ELEMENT unplug (description*)>
<!ELEMENT prop (description*, data?)>

<!--
 Meta data used for description and gdodoc.
 -->
<!ELEMENT description (#PCDATA)>
<!ELEMENT params_description (param0?, param1?, param2?, param3?, param4?, example*)>
<!ELEMENT param0 (#PCDATA)>
<!ELEMENT param1 (#PCDATA)>
<!ELEMENT param2 (#PCDATA)>
<!ELEMENT param3 (#PCDATA)>
<!ELEMENT param4 (#PCDATA)>
<!ELEMENT example (#PCDATA)>

<!--
 A default instance is defined by its java class and
 initial parameters.
 -->
<!ELEMENT param (#PCDATA)>
<!ELEMENT data (#PCDATA)>

<!--
 A stencil template is associated to a java class which may not
 have the same name. Extension can be defined by java hierarchy
 or explicitly defined (used if defined).
 Facets redefined the facets file name associated.
 -->
<!ATTLIST template
	java CDATA #IMPLIED
	extends CDATA #IMPLIED
	facets CDATA #IMPLIED
>

<!--
 A stencil is defined by a template.
 -->
<!ATTLIST stencil
	template CDATA #REQUIRED
	id CDATA #IMPLIED
	name CDATA #IMPLIED
>

<!--
 A slot is defined by a name and an arity. It can be dual (parent is key)
 and ordoned (comparator)
 Then it can be transient (not stored), calculated (java defined)
 or delegate (link to another one slot; then local or not)
 -->
<!ATTLIST slot
	name CDATA #REQUIRED
	
	arity CDATA #IMPLIED
	parent CDATA #IMPLIED
	comparator CDATA #IMPLIED
	calculated (true|false) "false"
	transient (true|false) "false"

	factory CDATA #IMPLIED

	depends CDATA #IMPLIED
	
	final (true|false) "false"
	override (true|false) "true"

	delegate CDATA #IMPLIED
	local (true|false) "true"
>

<!ATTLIST prop
	name CDATA #REQUIRED
	type (int|boolean|string) "string"
 	
	file CDATA #IMPLIED
	id CDATA #IMPLIED
	
	expand (true|false) "false"
	transient (true|false) "false"
	calculated (true|false) "false"
	
	final (true|false) "false"
	override (true|false) "true"
>

<!-- WARNING : no command in command or you will get an stack error.. 
     as any stencil (then a command has an unplug command which is a stencil..)
-->
<!ATTLIST command
	name CDATA #REQUIRED
	template CDATA #IMPLIED
	
	final (true|false) "false"
	override (true|false) "true"
>

<!ATTLIST inst
	id CDATA #REQUIRED
	name CDATA #IMPLIED
	template CDATA #REQUIRED
	
	file CDATA #IMPLIED
	encoding CDATA #IMPLIED
>

<!ATTLIST plug
	ref CDATA #REQUIRED
	path CDATA #IMPLIED
	slot CDATA #REQUIRED
	key CDATA #IMPLIED
	on (create|load|always) "create"
>

<!ATTLIST unplug
	slot CDATA #REQUIRED
	key CDATA #IMPLIED
	on (create|load|always) "create"
>

<!ATTLIST link
	slot CDATA #REQUIRED
	key CDATA #IMPLIED
	path CDATA #REQUIRED
>

<!ATTLIST default
	template CDATA #REQUIRED
>

<!--
 Expected java classes (interfaces), slots or commands that must be
 defined to accept the plug.
 -->
<!ATTLIST proto
	classes CDATA #IMPLIED
	slots CDATA #IMPLIED
	commands CDATA #IMPLIED
	props CDATA #IMPLIED
	template CDATA #IMPLIED
>

<!--
 Parameter defined for java construction or command execution.
 -->
<!ATTLIST param
	index CDATA #REQUIRED
	type CDATA #REQUIRED
>

=== duduklein/studiogdo/src/main/java/com/gdo/resource/cmd/AddResource.xml
<?xml version='1.0' encoding='iso-8859-1' ?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<template java="com.gdo.resource.cmd.AddResource">
	
	<params_description>
		<param0>Command should be performed for new resource or existing one :
			if 'new' : creates a new resource and the associated file.
			if 'get" : creates a resource from an already existing file.
		</param0>
		<param1>Resource template class name</param1>
		<param2>Command should perform Url encoding or not (values are :?)</param2>
	</params_description>
	
	<slot name="Contexts" delegate="Target/Contexts">
		<description>Predefined contextes used to retrieve predefined resources to import.</description>
	</slot>
	
	<prop name="SelectedContextPath" type="string"/>
	
	<slot name="SelectedContext" arity="1">
		<description>The context which will be used to complete the resource.</description>
	</slot>
	
	<prop name="CreationMode" type="string"/>
	
	<prop name="FileName" type="string"/>

	<slot name="ResourceCreated" arity="1">
		<description>The created resource will be stored here until its completion will be done.</description>
	</slot>
	
	<inst id="1" template="com.gdo.project.model.StepStcl">
		<description> Set Context for resource</description>
	</inst>
	
	<inst id="2" template="com.gdo.project.model.StepStcl">
		<description>Step will create specific resource(image/document)</description>
	</inst>
	
	<inst id="3" template="com.gdo.project.model.StepStcl">
		<description>Step will Plug the resource to ResourceCreated slot</description>
	</inst>
	
	<inst id="4" template="com.gdo.project.model.StepStcl">
		<description>Step will Plug the resource to ResourceMgr</description>
	</inst>
	
	<plug ref="1" key="1" slot="Steps"/>
	<plug ref="2" key="2" slot="Steps"/>
	<plug ref="3" key="3" slot="Steps"/>
	<plug ref="4" key="4" slot="Steps"/>
	
</template>

=== duduklein/studiogdo/src/main/java/com/gdo/project/cmd/CreateFilePropertyInOneStep.xml
<?xml version='1.0' encoding='utf-8' ?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<template java="com.gdo.project.cmd.CreateInOneStep">

	<description>Creates a property file stencil, validates it and then
		only plugs it in target slot.</description>
	<params_description>
		<param0>Set as simple propert, the value will be put in file after
			plug</param0>
		<param1>destination slot path (where the stencil created will be
			plugged in - relative to action)</param1>
		<param2>key type (none or string, int, uniquefor unicity - default :
			none) </param2>
		<param3>initial key value (default 1 for int, "a" for string)</param3>
		<param4>initial parameter for constructor if needed</param4>
	</params_description>

	<param0>com.gdo.project.PropStcl</param0>

</template>

=== duduklein/studiogdo/src/main/java/com/gdo/project/util/model/DateStcl.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<template java="com.gdo.project.util.model.DateStcl">

	<slot name="Now" calculated="true">
		<description>Date format as key (no key returns time int value)</description>
	</slot>
	<slot name="DateFormat" calculated="true">
		<description>Formatted date; number and string format as key
			(time:format)</description>
	</slot>

	<slot name="Year" calculated="true">
		<description>Date as key (now if no key)</description>
	</slot>
	<slot name="Month" calculated="true">
		<description>Date as key (now if no key)</description>
	</slot>
	<slot name="Day" calculated="true">
		<description>Date as key (now if no key)</description>
	</slot>
	<slot name="DayOfWeek" calculated="true">
		<description>Date as key (now if no key)</description>
	</slot>
	<slot name="DayOfYear" calculated="true">
		<description>Date as key (now if no key)</description>
	</slot>
	<slot name="Hour" calculated="true">
		<description>Date as key (now if no key)</description>
	</slot>

	<slot name="MonthName" calculated="true">
		<description>Month name; number and string format as key
			(number:format, ex. 3:%TB - on url interface 3:%25TB)</description>
	</slot>
	<slot name="DayName" calculated="true">
		<description>Day name; number and string format as key (number:format,
			ex. 1:%Ta - on url interface 1:%25Ta)</description>
	</slot>

</template>

=== duduklein/studiogdo/src/main/java/com/gdo/resource/direct/FileNameOrderedFolderResourceStcl.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<template extends="com.gdo.resource.model.DirectFolderResourceStcl">

	<description>
		Files and folders are sorted by name.
	</description>
	
	<!-- default template for folder -->
	<prop name="FolderTemplate" type="string"><data>com.gdo.resource.direct.FileNameOrderedFolderResourceStcl</data></prop>

	<!-- resources managed -->
	<slot name="FileResources" arity="*" calculated="true" comparator="string[Name]">
		<description>Contains all files managed</description>
	</slot>
	
	<slot name="FolderResources" arity="*" calculated="true" comparator="string[Name]">
		<description>Contains all folders managed</description>
	</slot>
</template>

=== duduklein/studiogdo/src/main/java/com/gdo/generator/model/GeneratorStcl.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<template java="com.gdo.generator.model.GeneratorStcl">

	<!-- mask used for expansion -->
	<prop name="Mask" type="string"/>

	<!-- mumber of expansion iteration (the result is expanded as many time) -->
	<prop name="Iteration" type="int"><data>1</data></prop>
	
	<!-- escape content (if defined all meta characters are escaped in result)  -->
	<!-- values are : (null), xml, html, java, javascript, sql -->
	<prop name="Escape" type="string"/>
	<slot name="Remove" arity="*">
		<description>exp to be removed from content defined as property and plugged here (done before escape)</description>
	</slot>
	
	
	<!-- sub generators defined for stencil chidren (key is mask mode) -->
	<slot name="Children" arity="*">
		<proto classes="com.gdo.generator.model.GeneratorStcl"/>
	</slot>
	
	<!-- Ftp context to retrieve resources in the editor -->
	<slot name="FtpContext" arity="?">
		<description>A FtpContext is set to retrieve resource to render them on editor.</description>
	</slot>
	
	<!-- files generated (contains at least one; key as url, value as property containing content) -->
	<slot name="FilesGenerated" arity="*" calculated="true"/>
	
	<!-- url file for generation (dir is used for ftp reading all ressource are from this dir) -->
	<prop name="Dir" type="string"/>
	<prop name="Url" type="string"/>
	
	<!-- boolean prop to allow directory creation -->
	<prop name="CreateDir" type="boolean"><data><![CDATA[false]]></data></prop>
	<!-- if true the url is used to generate a file -->
	<prop name="GenerateFile" type="boolean"><data><![CDATA[false]]></data></prop>
	<!-- if true the content is added to the file -->
	<prop name="AppendInFile" type="boolean"><data><![CDATA[false]]></data></prop>
	<!-- if true the text is return as expansion -->
	<prop name="GenerateText" type="boolean"><data><![CDATA[true]]></data></prop>

	<!-- used to defined if xinha should be used or not -->
	<prop name="IsHtml" type="boolean"><data>true</data></prop>

	<!-- contains the user id of the current writer (to be inherited form shared stencil) -->
	<prop name="InModification" type="boolean"><data>false</data></prop>
	
	<!-- trace on content generated -->
	<prop name="HtmlTrace" type="boolean"><data>true</data></prop>

	<command name="CreateSubGenerator" template="com.gdo.project.cmd.CreateAtomic">
		<description>Create a sub Generator in Children.</description>
		<param index="0" type="string">com.gdo.generator.model.GeneratorStcl</param>
		<param index="1" type="string">Target/Children</param>
		<param index="2" type="string">int</param>
		<param index="3" type="string">1</param>
	</command>

</template>

=== duduklein/studiogdo/src/main/java/com/gdo/project/cmd/Modify.xml
<?xml version='1.0' encoding='iso-8859-1' ?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<template java="com.gdo.project.cmd.Nothing">
	<description>
		Allow stencil modification.
		Select stencils from "Source"
		slots.
	</description>

	<!-- model part -->
	<slot name="Source" arity="*">
		<description>slot path where the selected stencils can be found (for
			selection)</description>
		<description>should be redefined (usually delegated slot)</description>
	</slot>

	<!-- used in rendering the command -->
	<prop name="StencilType" type="string">
		<data>stencil</data>
	</prop>

	<!-- presentation part -->
	<prop name="Title" id="title" />

	<!-- Modification Step -->
	<inst id="_1" template="com.gdo.project.model.StepStcl">
		<prop name="Title" id="step1.title" />
		<prop name="Render" id="step1.render" />
	</inst>

	<plug ref="_1" key="1" slot="Steps" />

</template>

=== duduklein/studiogdo/src/main/java/com/gdo/mail/model/IMAPMailStcl.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<template java="com.gdo.mail.model.IMAPMailStcl">

	<description>Mail associated to an inbox mail (imap)</description>
            
	<slot name="From" arity="1" calculated="true"/>
	<prop name="FromName" type="string" calculated="true"/>
	<prop name="SentDate" type="string" calculated="true"/>
	<slot name="To" arity="*" calculated="true"/>
	<slot name="CC" arity="*" calculated="true"/>
	<slot name="BCC" arity="*" calculated="true"/>
	<prop name="Title" type="string" calculated="true"/>
	<prop name="Content" type="string" calculated="true"/>
	
 	<command name="Delete" template="com.gdo.mail.cmd.DeleteIMAPMsg"/>

</template>

=== duduklein/studiogdo/src/main/java/com/gdo/project/cmd/service/Modify.xml
<?xml version='1.0' encoding='iso-8859-1' ?>

<!DOCTYPE template PUBLIC
  "-//StudioGdo//DTD Stencil 1.0//EN" "stencil.dtd">

<!-- todo should extends Modify -->
<template java="com.gdo.project.cmd.Nothing">

	<description>
		Set the default parameters for the service.
	</description>
	<params_description />

	<!-- presentation part -->
	<prop name="Title" id="title" />

	<!-- Creation Step -->
	<inst id="_1" template="com.gdo.project.model.StepStcl">
		<prop name="Title" id="step1.title" />
		<prop name="Render" id="step1.render" />
	</inst>

	<plug ref="_1" key="1" slot="Steps" />

</template>
